### ISSUE TITLE
Global SMTP configuration

### ISSUE THREAD

**Issue by zumbrunnen** [drone-plugins/drone-email#1]
In Drone 0.3.x it was possible to globally specify mailer settings in `drone.toml` like:

```toml
[smtp]
host="smtp.catcorp.cat"
port="587"
from="meow@catcorp.cat"
user="meow@catcorp.cat"
pass="meowmeow"
```

With 0.4 this possibility seems to be gone; each repository has to specify the settings in `.drone.yml` individually.

Wouldn't it be neat to bring back this feature? E.g. to have variables like these in `dronerc`:

```sh
# smtp configuration
SMTP_HOST=smtp.catcorp.cat
SMTP_PORT=587
SMTP_FROM="\"Ubercat\" <meow@catcorp.cat>"
SMTP_USER=meow@catcorp.cat
SMTP_PASS=meowmeow
```

And then, when `.drone.yml` doesn't specify any settings for sending e-mails, it will use those defaults? It would then be enough to specify something like this in `.drone.yml`:

```yaml
notify:
  email:
    when:
      success: false
      failure: true
```

Let me know if you think this is good idea. I think I could make such a contribution (PR).
