### ISSUE TITLE
I pass a template url, it does not work

### ISSUE THREAD

**Issue by allenlsy** [drone-plugins/drone-email#12]
my drone config file looks like:

```
notify:
  email:
    template: >
      http://github.com/abcdef
```

And I found the plugin recognise URL is `http://github.com/abcdef%0A`

So it cannot use my template
